// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5EcLp0m9fZxDCaKloOyolS3eowxnTkvs',
    appId: '1:764463780180:web:1faffe24c31efa711d78c1',
    messagingSenderId: '764463780180',
    projectId: 'my-app-877d5',
    authDomain: 'my-app-877d5.firebaseapp.com',
    storageBucket: 'my-app-877d5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6nvNHL_uHHINa_BuqgzYYDHtOBXenPGI',
    appId: '1:764463780180:android:bc4c7fd5b533efe81d78c1',
    messagingSenderId: '764463780180',
    projectId: 'my-app-877d5',
    storageBucket: 'my-app-877d5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRtGf8uqor8jMKNOk1Skp195-6N9W_eBQ',
    appId: '1:764463780180:ios:53834141df0508de1d78c1',
    messagingSenderId: '764463780180',
    projectId: 'my-app-877d5',
    storageBucket: 'my-app-877d5.appspot.com',
    iosBundleId: 'com.example.doczz.doczz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRtGf8uqor8jMKNOk1Skp195-6N9W_eBQ',
    appId: '1:764463780180:ios:53834141df0508de1d78c1',
    messagingSenderId: '764463780180',
    projectId: 'my-app-877d5',
    storageBucket: 'my-app-877d5.appspot.com',
    iosBundleId: 'com.example.doczz.doczz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5EcLp0m9fZxDCaKloOyolS3eowxnTkvs',
    appId: '1:764463780180:web:902d81d79b4e72c21d78c1',
    messagingSenderId: '764463780180',
    projectId: 'my-app-877d5',
    authDomain: 'my-app-877d5.firebaseapp.com',
    storageBucket: 'my-app-877d5.appspot.com',
  );
}
